### PR TITLE
New "Internetmarke" stamp layout

### PR DESCRIPTION
**Pull request by FabKre**
Hi Heinrich, 

Deutsche Post changed the default layout of their stamps. Some lengths had to be adapted.

Furthermore, the compact layout changed, thus some more slicing was needed. Actually, the compact-layout is alike to the Deutsche Post one, but some whitespaces were squashed in their compact version.

Maybe it does make sense to keep the old compact layout as _compact2_ or _compactold_!

Best regards
Fabian

### CODE REVIEW

**Comment by janheinrichmerker** [comment]
Oh, good catch. Didn't notice Deutsche Post changed its stamp format.
What if we introduced the new layout as new version, like `version=2019`, specified in the package or stamp options, so that people could still use their old stamps with this package. Basically it would be two new stamp layouts instead of updating the old ones.
I guess that's what you suggested by the `compactold` layout.

**Comment by janheinrichmerker** [comment]
Also when you compile, make sure the references in the documentation are resolved. You may need to run `pdflatex` twice.

**Comment by FabKre** [comment]
FYI: I'm very busy with my occupation. Thus doing the edits will take some time.

**Comment by janheinrichmerker** [comment]
No problem 😃 
I'm happy about your contribution!

**Comment by janheinrichmerker** [comment]
Will close #5.

**Comment by afh** [comment]
Thanks for writing the postage package @heinrichreimer and thanks to @FabKre for making the changes to adapt to the new layout of the Internetmarke.

It would be great to see this PR get merged and a new version of this package with the changes included be available.

What is missing to move ahead here?

**Comment by FabKre** [comment]
> What is missing to move ahead here?

I meant to add a package-option in order to support the old (early 2019) stamps. I'm afraid I haven't any time for that, though. Implementing those changes was always on low priority and is probably expandable, in the meantime.

**Comment by afh** [comment]
Thanks for the quick response, @FabKre.
For what it's worth I think there is more value in merging this PR and removing support for old stamps (for the time being) than this useful package to not work with the current layout of the Internetmarke.

**Comment by janheinrichmerker** [comment]
Okay, let's merge the PR then!
I noticed, in the PDF some references are broken.
Could you please fix that?
I'll commit my new LaTeX build pipeline (that I developed for another latex package) so that we can send the new version to CTAN tomorrow.

**Comment by FabKre** [comment]
had to squash all commits because of CLA (the older commits were done without email).

**Comment by afh** [comment]
🙌 Thank you @heinrichreimer and @FabKre for moving so quickly here. I look forward to seeing a new version of the package in `tlmgr update --list`.

Have the broken references been addressed @heinrichreimer? If not, it's something I could potentially look into…

**Comment by janheinrichmerker** [comment]
@FabKre already fixed the broken references when squashing commits.

**Pull request merged**
